server {
    listen 8080;
    host 0.0.0.0;
    server_name localhost;
    client_max_body_size 1M;
    root ./www;
    index index.html;
	#error_page 404 /errors/404.html;
	#error_page 500 /errors/50x.html;
	
    location / {
        allow_methods GET;
    }

    location /directory/ {
        root ./YoupiBanane;
        index youpi.bad_extension;
        allow_methods GET;
    }

    location /post_body {
        root ./www/post_body;
        allow_methods POST DELETE;
        client_max_body_size 100;
    }

    location /uploads {
        root ./www/uploads;
        allow_methods POST GET;
        client_max_body_size 100;
    }

	location /errors/ {
    	root ./www/errors;
    	allow_methods GET;
    	autoindex on;
	}
	location /cgi-bin/ {
        root ./www/cgi-bin;
        allow_methods GET POST;
        cgi_path /usr/bin/python3;
        cgi_extension .py;
    }
	location /old {
    	return 301 /;
	}
}

server {
    listen 8080;
    host 0.0.0.0;
    server_name other;
    client_max_body_size 1M;
    root ./www_test;
    index test.html;

    location / {
        allow_methods GET;
    }

    location /post_body {
        root ./www;
        allow_methods POST;
        client_max_body_size 100;
    }

    location /YoupiBanane/ {
        root ./YoupiBanane;
        allow_methods POST;
        cgi_path ./cgi_tester;
        cgi_extension .bla;
    }

	location /cgi-bin/ {
        root ./www/cgi-bin;
        allow_methods GET POST;
        cgi_path /usr/bin/python3;
        cgi_extension .py;
    }
}

server {
    listen 8081;
    host 0.0.0.0;
    server_name second.local;
    root ./www_test;
    index test.html;
    location / {
        allow_methods GET;
    }
}