# ==========================================
# WEBSERV CONFIGURATION FILE
# ==========================================

# --- SERVER BLOCK 1: The Main Website ---
server {
    # 1. Port and Host/IP
	#token token
	#directive value
    listen 8080;
    host 127.0.0.1;

    # 2. Domain names (can be multiple)
    server_name localhost example.com;

    # 3. Limit for POST requests (e.g., 10 Megabytes)
    client_max_body_size 10M;

    # 4. Default error pages
    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    # 5. Global rules for this server
    root ./www;
    index index.html default.html;

    # --- LOCATION BLOCK A: The Default Route ---
    location / {
        allow_methods GET;
        autoindex on;
    }

    # --- LOCATION BLOCK B: The Upload Folder ---
    location /uploads {
        allow_methods GET POST DELETE;
        root ./www/uploads;
        autoindex off;
    }

    # --- LOCATION BLOCK C: Redirection ---
    # If a user goes to /old_site, redirect them to /
    location /old_site {
        return 301 /;
    }

    # --- LOCATION BLOCK D: CGI Execution ---
    location /cgi-bin {
        allow_methods GET POST;
        root ./www/cgi-bin;
        cgi_extension .py .php;
        cgi_path /usr/bin/python3; 
    }
}

# --- SERVER BLOCK 2: A Second Website ---
# Your parser must handle multiple servers in one file!
server {
    listen 8081;
    server_name test.localhost;
    root ./www_test;

    location / {
        allow_methods GET;
        index test.html;
    }
}